# Generated by Django 4.2.8 on 2023-12-25 13:48

from django.db import migrations, models
import index.validators
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('isbn', models.CharField(max_length=50, verbose_name='Shabak')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('age_group', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'J'), (4, 'D'), (5, 'H'), (6, 'Undefined')], default=6)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('latest_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Latest update date')),
                ('reading_date', models.DateTimeField(verbose_name='Reading date')),
                ('status', models.BooleanField(default=False, verbose_name='Currently reading?')),
                ('file', models.FileField(upload_to='BookPDF/', validators=[index.validators.validate_file_extension])),
                ('page_num_for_cover', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='BookCovers/')),
                ('category', models.ManyToManyField(blank=True, to='index.category', verbose_name='Category(s)')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
