# Generated by Django 4.2.8 on 2023-12-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='latest_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Latest update date'),
        ),
    ]
