# Generated by Django 4.2.8 on 2023-12-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_book_reading_date_book_reading_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reading_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reading date (end)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reading_date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reading date (start)'),
        ),
    ]
